
DROP TABLE BEVERAGES;

CREATE TABLE BEVERAGES(
	ITEM_CODE 				VARCHAR(14) NOT NULL,
	ITEM_NAME				VARCHAR(30) NOT NULL,
	ITEM_PRICE				DECIMAL(10,2)
	);

ALTER TABLE BEVERAGES ADD CONSTRAINT BEVERAGES_PK PRIMARY KEY (ITEM_CODE);

--COMMENT ON TABLE BEVERAGES  IS 'BEVERAGES';

INSERT INTO BEVERAGES (ITEM_CODE, ITEM_NAME, ITEM_PRICE) VALUES ('1', 'Tea', 10.00);
INSERT INTO BEVERAGES (ITEM_CODE, ITEM_NAME, ITEM_PRICE) VALUES ('2', 'Coffee', 10.00);
INSERT INTO BEVERAGES (ITEM_CODE, ITEM_NAME, ITEM_PRICE) VALUES ('3', 'Bottle', 10.00);
INSERT INTO BEVERAGES (ITEM_CODE, ITEM_NAME, ITEM_PRICE) VALUES ('4', 'ColdDrink', 15.00);

