DROP TABLE CUSTOMER_MATCHES_RECORD;

CREATE TABLE CUSTOMER_MATCHES_RECORD(
	CUST_ENTRY_NO 			VARCHAR(14)		NOT NULL,
	MATCH_NO 				VARCHAR(14)   	NOT NULL,
	BUSINESS_DATE			VARCHAR(10)   	NOT NULL,
	CUST_ID					VARCHAR(14)		NOT NULL,
	FRAME_TYPE				VARCHAR(14),
	CUST_MATCHES_TOTAL_BILL	INTEGER			DEFAULT 0,
	CREATION_TIME			TIMESTAMP,
	MODIFICATION_TIME		TIMESTAMP
	);

ALTER TABLE CUSTOMER_MATCHES_RECORD ADD CONSTRAINT CUSTOMER_MATCHES_RECORD_PK PRIMARY KEY 
(CUST_ENTRY_NO, MATCH_NO, BUSINESS_DATE, CUST_ID);

COMMENT ON TABLE BUSINESS  IS 'CUSTOMER_MATCHES_RECORD';

