package com.projectwork.impl.sql;

public interface BeveragesServiceSQLIfc
{
    String GET_BEVERAGES_DETAILS = "SELECT ITEM_CODE, ITEM_NAME, ITEM_PRICE FROM BEVERAGES";

    String ADD_CUSTOMER_BEVERAGE_DETAILS = "INSERT INTO CUSTOMER_BEVERAGES_RECORD(CUST_ENTRY_NO, CUST_ID, BUSINESS_DATE, "
            + " CREATION_TIME, MODIFICATION_TIME) VALUES (?,?,?,?,?)";

    String GET_CUSTOMER_BEVERAGE_DETAILS = "SELECT CUST_ENTRY_NO, BUSINESS_DATE, TEA_QTY, COFFEE_QTY, BOTTLE_QTY, COLDDRINK_QTY, CUST_BEV_TOTAL_BILL "
            + " FROM CUSTOMER_BEVERAGES_RECORD WHERE CUST_ID = ? AND BUSINESS_DATE = ?";

    String UPDATE_CUSTOMER_BEVERAGES_DETAILS = "UPDATE CUSTOMER_BEVERAGES_RECORD SET TEA_QTY=?, COFFEE_QTY=?, BOTTLE_QTY=?, "
            + " COLDDRINK_QTY=?, CUST_BEV_TOTAL_BILL=?, MODIFICATION_TIME = ? WHERE CUST_ENTRY_NO = ?";

}
