package com.projectwork.impl.sql;

public interface CustomerMatchesServiceSQLIfc
{
    String ADD_CUSTOMER_MATCH_RECORD = "INSERT INTO CUSTOMER_MATCHES_RECORD(CUST_ENTRY_NO, MATCH_NO, BUSINESS_DATE, CUST_ID, "
            + " FRAME_TYPE, CREATION_TIME, MODIFICATION_TIME) VALUES (?,?,?,?,?,?,?)";

    String GET_CUSTOMER_MATCH_RECORD = "SELECT CUST_ENTRY_NO, BUSINESS_DATE, CUST_ID FROM CUSTOMER_MATCHES_RECORD WHERE MATCH_NO = ? "
            + " ORDER BY CUST_ID";
    
    String UPDATE_PAYEE_BILL_RECORD = "UPDATE CUSTOMER_MATCHES_RECORD SET CUST_MATCHES_TOTAL_BILL = ?, MODIFICATION_TIME =? "
            + " WHERE CUST_ID = ? AND MATCH_NO = ? ";

    String GET_CUSTOMER_ALL_CURRENT_MATCHES_RECORD = "SELECT CUST_ENTRY_NO, MATCH_NO, BUSINESS_DATE, CUST_ID, FRAME_TYPE, "
            + " CUST_MATCHES_TOTAL_BILL FROM CUSTOMER_MATCHES_RECORD WHERE CUST_ENTRY_NO = ? ORDER BY MATCH_NO";

    String GET_CUSTOMER_TODAYS_MATCHES_RECORD = "SELECT t1.CUST_ENTRY_NO, t1.MATCH_NO, t1.BUSINESS_DATE, t1.CUST_ID, t1.FRAME_TYPE, "
            + " t1.CUST_MATCHES_TOTAL_BILL, t2.EMP_ID, t2.TABLE_NO, t2.FRAME_START_TIME, t2.FRAME_END_TIME, t2.MATCH_STATUS FROM "
            + " CUSTOMER_MATCHES_RECORD t1, BUSINESS_DAY_MATCHES t2 WHERE t1.MATCH_NO = t2.MATCH_NO AND t1.CUST_ID = ? "
            + " AND t1.BUSINESS_DATE = ? AND t2.MATCH_STATUS != 'Cancelled' ORDER BY t1.MATCH_NO";

}
